name: Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    env:
      VERSION: $(date +%s)
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Docker Build
        run: docker build -t blog-api .
        
      - name: Docker Tag
        run: docker tag blog-api kongebra/blog-api:latest
        
      - name: Docker Push
        run: docker push kongebra/blog-api:latest
