name: Docker
on:
  push:
    branches:
      - master
      - release/*
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERSION: $(date +%s)
    steps:
      - uses: actions/checkout@v1
      - name: Login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build
        run: docker build --tag kongebra/blog-api:latest .
        
      - name: Tag
        run: docker tag kongebra/blog-api:latest kongebra/blog-api:${{ VERSION }}
        
      - name: Publish
        run: docker push kongebra/blog-api:${{ VERSION }}
