name: Docker Image CI

on:
  push:
    branches: 
      - master
      - release/*
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kongebra/blog-api:$(date +%s)
